"""add comentarios table

Revision ID: 5da6ff196c08
Revises: ba6275174718
Create Date: 2025-07-02 14:25:47.580381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da6ff196c08'
down_revision = 'ba6275174718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('autor', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mensagem'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    # ### end Alembic commands ###
