"""atualizando model e schema de usuario

Revision ID: 7a6388290c9a
Revises: 59a14617d4dd
Create Date: 2025-08-07 18:09:50.278249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6388290c9a'
down_revision = '59a14617d4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.String(length=5), nullable=True))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###
