"""incluindo relacionamento entre usuario e message

Revision ID: ba6275174718
Revises: 48ec7a0fa6f8
Create Date: 2025-06-19 00:04:29.904932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6275174718'
down_revision = '48ec7a0fa6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mensagens_user_id', 'users', ['autor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mensagens_user_id', type_='foreignkey')
        batch_op.drop_column('autor')

    op.drop_table('users')
    # ### end Alembic commands ###
